server:
  port: 4000

database:
  driver: "postgres"
  url: "postgres://postgres:123123@localhost:5432/postgres?sslmode=disable"

email:
  smtp_host: "smtp.mail.ru"
  smtp_port: 465
  smtp_user: "user@internet.ru"
  smtp_password: "MdZ19VQzAeXEzlFA4xRN"
  from_email: "user@internet.ru"
